<a href="https://colab.research.google.com/github/Tselovanska/machine-learning-course/blob/main/HW_2_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [36]:
my_vector = np.random.uniform(0,1,10)

my_matrix = np.array([[11,14,17],
                     [20,23,26],
                     [29,32,35]])

print(f"Вектор: {my_vector}\nРозмір вектора: {my_vector.shape}\n")
print(f"Матриця: {my_matrix}\nРозмір матриці: {my_matrix.shape}")


Вектор: [0.93728736 0.85512792 0.14315263 0.3036211  0.16779713 0.16160584
 0.02135621 0.89995843 0.54116999 0.06467719]
Розмір вектора: (10,)

Матриця: [[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмір матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [37]:
my_vector = np.round(my_vector * 10, decimals=2)
my_vector

array([9.37, 8.55, 1.43, 3.04, 1.68, 1.62, 0.21, 9.  , 5.41, 0.65])

In [38]:
my_matrix = my_matrix * 2
my_matrix

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [39]:
new_vector = np.round(my_vector **2, decimals=2)
new_vector

array([8.780e+01, 7.310e+01, 2.040e+00, 9.240e+00, 2.820e+00, 2.620e+00,
       4.000e-02, 8.100e+01, 2.927e+01, 4.200e-01])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [40]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [41]:
result_matrix = np.dot(B,A)
result_matrix, result_matrix.shape

(array([[0.7281, 0.5202],
        [0.2034, 0.2846]]),
 (2, 2))

In [42]:
C_two = np.dot(result_matrix, C)
C_two

array([[0.5202],
       [0.2846]])

In [43]:
D_two = np.dot(result_matrix, D)
D_two

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [44]:
transponed_matrix = result_matrix.T
result_matrix, transponed_matrix

(array([[0.7281, 0.5202],
        [0.2034, 0.2846]]),
 array([[0.7281, 0.2034],
        [0.5202, 0.2846]]))

In [45]:
transponed_vector = my_vector.T
my_vector, transponed_vector

(array([9.37, 8.55, 1.43, 3.04, 1.68, 1.62, 0.21, 9.  , 5.41, 0.65]),
 array([9.37, 8.55, 1.43, 3.04, 1.68, 1.62, 0.21, 9.  , 5.41, 0.65]))

Ні, бо траспонування на одновимірний вектор нічого не робить.

In [46]:
column_vector = np.expand_dims(my_vector, axis=1)

my_vector, column_vector

(array([9.37, 8.55, 1.43, 3.04, 1.68, 1.62, 0.21, 9.  , 5.41, 0.65]),
 array([[9.37],
        [8.55],
        [1.43],
        [3.04],
        [1.68],
        [1.62],
        [0.21],
        [9.  ],
        [5.41],
        [0.65]]))

In [47]:
transponed_column_vector = column_vector.T

transponed_column_vector, transponed_column_vector.shape

(array([[9.37, 8.55, 1.43, 3.04, 1.68, 1.62, 0.21, 9.  , 5.41, 0.65]]),
 (1, 10))